name: convert

on: 
  push:
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'overrides'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Pre-convert
        run: |
          bash convert.sh
      # - name: Convert via pandoc
      #   uses: docker://pandoc/core:2.9
      #   with:
      #     args: "-s ./docs/Ezotero_intro.tex -o ./docs/Ezotero.md" 
      - name: Post-convert
        run: |
          tree
          cat ./docs/Ezotero.md
          rm ./docs/*.tex
          bash split.sh                  
          bash commit.sh


