name: convert

on: 
  push:
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'overrides'

jobs:
  convert:
    runs-on: ubuntu-18.04
    steps:
      - run: bash convert.sh             # 转换前置准备
      - uses: docker://pandoc/core:2.9   # 使用 pandoc 将 .tex 转为 .md 
        with:
          args: "-s ./docs/Ezotero_intro.tex -o ./docs/Ezotero.md" 
      - run: |
          bash split.sh                  # 将生成的 .md 按标题级别拆分
          bash commit.sh


