name: convert

on: 
  push:
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'overrides'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Pre-convert
        run: |
          bash convert.sh
      - name: Convert via pandoc
        uses: docker://pandoc/core:latest
        with:
          args: "-s ./docs/Ezotero_intro.tex -o ./docs/Ezotero.md --markdown-headings=atx -t markdown+ignore_line_breaks+hard_line_breaks" 
      - name: Post-convert
        run: |
          # tree
          # cat ./docs/Ezotero.md
          bash split.sh
          bash clean.sh
          bash commit.sh
      - uses: actions/setup-python@v3
        with:
          python-version: 3.10.2
      - name: Mkdocs build
        run: |
          pip install -r requirements.txt
          mkdocs gh-deploy --force --clean

